# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Lab1_security(object):
    def setupUi(self, Lab1_security):
        Lab1_security.setObjectName("Lab1_security")
        Lab1_security.resize(720, 720)
        self.label_choose_role = QtWidgets.QLabel(Lab1_security)
        self.label_choose_role.setGeometry(QtCore.QRect(10, 40, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_choose_role.setFont(font)
        self.label_choose_role.setObjectName("label_choose_role")
        self.button_start = QtWidgets.QPushButton(Lab1_security)
        self.button_start.setGeometry(QtCore.QRect(10, 110, 701, 25))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_start.setFont(font)
        self.button_start.setObjectName("button_start")
        self.label_pwd = QtWidgets.QLabel(Lab1_security)
        self.label_pwd.setGeometry(QtCore.QRect(0, 160, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_pwd.setFont(font)
        self.label_pwd.setObjectName("label_pwd")
        self.line_edit_pwd = QtWidgets.QLineEdit(Lab1_security)
        self.line_edit_pwd.setGeometry(QtCore.QRect(50, 160, 611, 31))
        self.line_edit_pwd.setObjectName("line_edit_pwd")
        self.button_pwd = QtWidgets.QPushButton(Lab1_security)
        self.button_pwd.setGeometry(QtCore.QRect(668, 160, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_pwd.setFont(font)
        self.button_pwd.setObjectName("button_pwd")
        self.label_ls = QtWidgets.QLabel(Lab1_security)
        self.label_ls.setGeometry(QtCore.QRect(0, 220, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_ls.setFont(font)
        self.label_ls.setObjectName("label_ls")
        self.line_edit_ls = QtWidgets.QLineEdit(Lab1_security)
        self.line_edit_ls.setGeometry(QtCore.QRect(50, 210, 611, 31))
        self.line_edit_ls.setObjectName("line_edit_ls")
        self.button_ls = QtWidgets.QPushButton(Lab1_security)
        self.button_ls.setGeometry(QtCore.QRect(668, 210, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_ls.setFont(font)
        self.button_ls.setObjectName("button_ls")
        self.label_cd = QtWidgets.QLabel(Lab1_security)
        self.label_cd.setGeometry(QtCore.QRect(0, 270, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_cd.setFont(font)
        self.label_cd.setObjectName("label_cd")
        self.button_cd = QtWidgets.QPushButton(Lab1_security)
        self.button_cd.setGeometry(QtCore.QRect(668, 260, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_cd.setFont(font)
        self.button_cd.setObjectName("button_cd")
        self.line_edit_cd = QtWidgets.QLineEdit(Lab1_security)
        self.line_edit_cd.setGeometry(QtCore.QRect(50, 260, 611, 31))
        self.line_edit_cd.setObjectName("line_edit_cd")
        self.label_mkdir = QtWidgets.QLabel(Lab1_security)
        self.label_mkdir.setGeometry(QtCore.QRect(0, 320, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_mkdir.setFont(font)
        self.label_mkdir.setObjectName("label_mkdir")
        self.line_edit_mkdir = QtWidgets.QLineEdit(Lab1_security)
        self.line_edit_mkdir.setGeometry(QtCore.QRect(70, 310, 571, 31))
        self.line_edit_mkdir.setText("")
        self.line_edit_mkdir.setObjectName("line_edit_mkdir")
        self.button_mkdir = QtWidgets.QPushButton(Lab1_security)
        self.button_mkdir.setGeometry(QtCore.QRect(648, 310, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_mkdir.setFont(font)
        self.button_mkdir.setObjectName("button_mkdir")
        self.label_vi = QtWidgets.QLabel(Lab1_security)
        self.label_vi.setGeometry(QtCore.QRect(0, 470, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_vi.setFont(font)
        self.label_vi.setObjectName("label_vi")
        self.line_edit_vi = QtWidgets.QLineEdit(Lab1_security)
        self.line_edit_vi.setGeometry(QtCore.QRect(70, 460, 571, 31))
        self.line_edit_vi.setText("")
        self.line_edit_vi.setObjectName("line_edit_vi")
        self.button_vi = QtWidgets.QPushButton(Lab1_security)
        self.button_vi.setGeometry(QtCore.QRect(648, 460, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_vi.setFont(font)
        self.button_vi.setObjectName("button_vi")
        self.label_rmfile = QtWidgets.QLabel(Lab1_security)
        self.label_rmfile.setGeometry(QtCore.QRect(0, 370, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_rmfile.setFont(font)
        self.label_rmfile.setObjectName("label_rmfile")
        self.line_edit_rmfile = QtWidgets.QLineEdit(Lab1_security)
        self.line_edit_rmfile.setGeometry(QtCore.QRect(70, 360, 571, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.line_edit_rmfile.setFont(font)
        self.line_edit_rmfile.setText("")
        self.line_edit_rmfile.setObjectName("line_edit_rmfile")
        self.button_rmfile = QtWidgets.QPushButton(Lab1_security)
        self.button_rmfile.setGeometry(QtCore.QRect(648, 360, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_rmfile.setFont(font)
        self.button_rmfile.setObjectName("button_rmfile")
        self.button_rmdir = QtWidgets.QPushButton(Lab1_security)
        self.button_rmdir.setGeometry(QtCore.QRect(648, 410, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_rmdir.setFont(font)
        self.button_rmdir.setObjectName("button_rmdir")
        self.line_edit_rmdir = QtWidgets.QLineEdit(Lab1_security)
        self.line_edit_rmdir.setGeometry(QtCore.QRect(70, 410, 571, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.line_edit_rmdir.setFont(font)
        self.line_edit_rmdir.setText("")
        self.line_edit_rmdir.setObjectName("line_edit_rmdir")
        self.label_rmdir = QtWidgets.QLabel(Lab1_security)
        self.label_rmdir.setGeometry(QtCore.QRect(0, 420, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_rmdir.setFont(font)
        self.label_rmdir.setObjectName("label_rmdir")
        self.text_edit_vi = QtWidgets.QPlainTextEdit(Lab1_security)
        self.text_edit_vi.setGeometry(QtCore.QRect(10, 500, 701, 181))
        self.text_edit_vi.setPlainText("")
        self.text_edit_vi.setObjectName("text_edit_vi")
        self.label_root = QtWidgets.QLabel(Lab1_security)
        self.label_root.setGeometry(QtCore.QRect(340, 30, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_root.setFont(font)
        self.label_root.setObjectName("label_root")
        self.label_user = QtWidgets.QLabel(Lab1_security)
        self.label_user.setGeometry(QtCore.QRect(340, 50, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_user.setFont(font)
        self.label_user.setObjectName("label_user")
        self.label_blocked_user = QtWidgets.QLabel(Lab1_security)
        self.label_blocked_user.setGeometry(QtCore.QRect(340, 70, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_blocked_user.setFont(font)
        self.label_blocked_user.setObjectName("label_blocked_user")
        self.button_end = QtWidgets.QPushButton(Lab1_security)
        self.button_end.setGeometry(QtCore.QRect(10, 690, 701, 25))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_end.setFont(font)
        self.button_end.setObjectName("button_end")

        self.retranslateUi(Lab1_security)
        QtCore.QMetaObject.connectSlotsByName(Lab1_security)

    def retranslateUi(self, Lab1_security):
        _translate = QtCore.QCoreApplication.translate
        Lab1_security.setWindowTitle(_translate("Lab1_security", "Lab1_security"))
        self.label_choose_role.setText(_translate("Lab1_security", "You are blocked_user (unknown)"))
        self.button_start.setText(_translate("Lab1_security", "Start"))
        self.label_pwd.setText(_translate("Lab1_security", "pwd"))
        self.button_pwd.setText(_translate("Lab1_security", "pwd"))
        self.label_ls.setText(_translate("Lab1_security", "ls"))
        self.button_ls.setText(_translate("Lab1_security", "ls"))
        self.label_cd.setText(_translate("Lab1_security", "cd"))
        self.button_cd.setText(_translate("Lab1_security", "cd"))
        self.label_mkdir.setText(_translate("Lab1_security", "mkdir"))
        self.button_mkdir.setText(_translate("Lab1_security", "mkdir"))
        self.label_vi.setText(_translate("Lab1_security", "vi"))
        self.button_vi.setText(_translate("Lab1_security", "vi"))
        self.label_rmfile.setText(_translate("Lab1_security", "rmfile"))
        self.button_rmfile.setText(_translate("Lab1_security", "rmfile"))
        self.button_rmdir.setText(_translate("Lab1_security", "rmdir"))
        self.label_rmdir.setText(_translate("Lab1_security", "rmdir"))
        self.label_root.setText(_translate("Lab1_security", "# Root has all rights (rwx)"))
        self.label_user.setText(_translate("Lab1_security", "# User has limited rights (r-x)"))
        self.label_blocked_user.setText(_translate("Lab1_security", "# Blocked user has not rights (---)"))
        self.button_end.setText(_translate("Lab1_security", "End"))
